## Numpy Tutorial
![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

## Numpy Axis
![](https://i.stack.imgur.com/h1alT.jpg)

In [2]:
import numpy as np

## Array Declaration

In [36]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr.ndim

2

In [38]:
arr.dtype

dtype('int64')

In [39]:
arr.shape

(2, 3)

In [40]:
arr.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
arr = np.arange(80)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [42]:
arr = arr.reshape(4, 5, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [43]:
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [44]:
arr = np.zeros((5, 4, 5))
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [45]:
arr = np.ones((5, 4, 10))
arr

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1

In [46]:
#it will have random values based on time...
arr = np.empty((2, 2, 5), dtype=np.int64)
arr

array([[[4636051196098904064, 4634784558703706112, 4633113301029486592,
         4631142976192512000, 4629207835727626240],
        [4626393085960519680, 4623085754984169472, 4618722892845154304,
         4612248968380809216, 4598175219545276416]],

       [[4598175219545276416, 4612248968380809216, 4618722892845154304,
         4623085754984169472, 4626393085960519680],
        [4629207835727626240, 4631142976192512000, 4633113301029486592,
         4634784558703706112, 4636051196098904064]]])

In [47]:
arr = np.full((5, 4), 10)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [48]:
#Create an eye matrix with 1s at its diagonals...
arr = np.eye(5, 4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [49]:
arr = np.arange(0, 40).reshape(2, 5, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [50]:
np.random.uniform(5, 10, (4, 3, 2))

array([[[9.47840435, 9.98295045],
        [7.59321013, 7.41511576],
        [9.15144613, 8.35013517]],

       [[7.76562805, 9.34087243],
        [6.29131152, 9.00599308],
        [9.6684863 , 6.0553007 ]],

       [[5.88942339, 6.81930187],
        [5.2425857 , 7.65816798],
        [9.22920776, 6.2858553 ]],

       [[8.87076987, 9.72784459],
        [9.24324498, 9.05868742],
        [7.15972202, 6.59238098]]])

In [51]:
arr = np.random.rand(5, 4)
arr

array([[0.47940939, 0.61723404, 0.58996089, 0.21440999],
       [0.90905963, 0.16986989, 0.59091258, 0.60311842],
       [0.41784509, 0.34692629, 0.53887453, 0.54389177],
       [0.58158266, 0.19485468, 0.05456807, 0.77518061],
       [0.20891385, 0.26796836, 0.48105768, 0.14534376]])

In [52]:
arr = np.random.randint(10, 50, (5, 4))
arr

array([[29, 48, 12, 26],
       [41, 46, 40, 44],
       [21, 11, 10, 49],
       [24, 18, 40, 24],
       [32, 42, 31, 26]])

In [53]:
arr = np.random.randint(10, 50, (2, 3, 3, 4))
arr

array([[[[45, 23, 41, 11],
         [16, 26, 36, 44],
         [24, 25, 25, 18]],

        [[24, 18, 32, 26],
         [18, 28, 18, 39],
         [44, 38, 31, 14]],

        [[35, 47, 20, 37],
         [31, 40, 21, 46],
         [18, 15, 20, 34]]],


       [[[21, 19, 18, 39],
         [23, 28, 33, 47],
         [44, 21, 49, 16]],

        [[20, 40, 42, 14],
         [41, 27, 16, 14],
         [29, 33, 49, 31]],

        [[33, 39, 43, 28],
         [15, 29, 22, 15],
         [44, 39, 36, 27]]]])

In [91]:
#normal(mean, std, size)
arr = np.random.normal(0.0, 5.0, 20)
arr

array([ 6.63685678, -3.38640038,  2.23683677, -1.19427915, -4.64502762,
       11.11270803, -3.41332138, -3.14233872, -3.53670796, -2.47964074,
       -1.69741817, -5.43872133, -4.19083335,  2.81363696,  4.64476016,
        6.49094716,  1.66950389, -0.29104336,  3.82343801, -7.28809767])

In [92]:
arr.mean()

-0.06375710430259099

In [93]:
arr.std()

4.68704756900972

## Array Indexing & Slicing 

In [62]:
arr = np.arange(240).reshape(3, 4, 4, 5)
arr

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]]],


       [[[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]],

        [[120, 121, 122, 123, 124],
         [125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134],
         [135,

In [63]:
arr[:, [0, 1, 2, 3], [0, 1, 2, 3]]

array([[[  0,   1,   2,   3,   4],
        [ 25,  26,  27,  28,  29],
        [ 50,  51,  52,  53,  54],
        [ 75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84],
        [105, 106, 107, 108, 109],
        [130, 131, 132, 133, 134],
        [155, 156, 157, 158, 159]],

       [[160, 161, 162, 163, 164],
        [185, 186, 187, 188, 189],
        [210, 211, 212, 213, 214],
        [235, 236, 237, 238, 239]]])

In [64]:
index = np.where(arr %2 == 0)

In [66]:
arr[index]

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238])

In [65]:
#Difference between arr[0] and arr[:1]
arr[0]#it will change the shape of ouput...

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]]])

In [67]:
arr[:1]#the output will be of the same shape...

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]]]])

In [69]:
arr[1, :2, :, 1:3]

array([[[ 81,  82],
        [ 86,  87],
        [ 91,  92],
        [ 96,  97]],

       [[101, 102],
        [106, 107],
        [111, 112],
        [116, 117]]])

In [94]:
arr = np.arange(27)
arr = arr.reshape(3, 3, 3)

In [95]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
arr[1:, [0, 1], [1, 2]]

array([[10, 14],
       [19, 23]])

In [97]:
arr = np.arange(200)
arr = arr.reshape(10, 5, 4)
arr

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19]],

       [[ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31],
        [ 32,  33,  34,  35],
        [ 36,  37,  38,  39]],

       [[ 40,  41,  42,  43],
        [ 44,  45,  46,  47],
        [ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59]],

       [[ 60,  61,  62,  63],
        [ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79]],

       [[ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95],
        [ 96,  97,  98,  99]],

       [[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119]],

       [[120, 121, 122, 123],
        [124, 125, 126, 127],
        [128, 129, 130, 131]

In [98]:
arr[:, :, 0]

array([[  0,   4,   8,  12,  16],
       [ 20,  24,  28,  32,  36],
       [ 40,  44,  48,  52,  56],
       [ 60,  64,  68,  72,  76],
       [ 80,  84,  88,  92,  96],
       [100, 104, 108, 112, 116],
       [120, 124, 128, 132, 136],
       [140, 144, 148, 152, 156],
       [160, 164, 168, 172, 176],
       [180, 184, 188, 192, 196]])

## Array Sorting 

In [53]:
np.sort(arr, axis=1)

array([[17, 26, 35, 43],
       [17, 19, 22, 29],
       [11, 19, 31, 41],
       [10, 19, 22, 42],
       [15, 16, 22, 29]])

In [54]:
np.sort(arr, axis=0)

array([[15, 11, 16, 10],
       [17, 19, 17, 26],
       [19, 22, 19, 29],
       [35, 22, 22, 29],
       [41, 43, 42, 31]])

In [63]:
np.sort(arr, axis=0)

array([[[[24, 14, 33, 37],
         [11, 35, 21, 21],
         [30, 40, 20, 29]],

        [[41, 10, 17, 16],
         [15, 12, 13, 15],
         [12, 15, 31, 16]],

        [[18, 19, 33, 18],
         [10, 11, 18, 18],
         [11, 21, 14, 36]]],


       [[[28, 38, 42, 42],
         [43, 45, 32, 35],
         [31, 42, 25, 35]],

        [[43, 15, 26, 43],
         [38, 31, 43, 17],
         [48, 18, 32, 32]],

        [[30, 49, 43, 22],
         [17, 40, 44, 41],
         [27, 29, 26, 36]]]])

In [65]:
arr

array([[[[28, 14, 42, 42],
         [11, 35, 32, 21],
         [31, 40, 25, 35]],

        [[41, 10, 17, 16],
         [38, 31, 13, 15],
         [12, 18, 31, 32]],

        [[30, 19, 43, 22],
         [10, 11, 18, 41],
         [11, 29, 26, 36]]],


       [[[24, 38, 33, 37],
         [43, 45, 21, 35],
         [30, 42, 20, 29]],

        [[43, 15, 26, 43],
         [15, 12, 43, 17],
         [48, 15, 32, 16]],

        [[18, 49, 33, 18],
         [17, 40, 44, 18],
         [27, 21, 14, 36]]]])

In [64]:
np.sort(arr, axis=1)

array([[[[28, 10, 17, 16],
         [10, 11, 13, 15],
         [11, 18, 25, 32]],

        [[30, 14, 42, 22],
         [11, 31, 18, 21],
         [12, 29, 26, 35]],

        [[41, 19, 43, 42],
         [38, 35, 32, 41],
         [31, 40, 31, 36]]],


       [[[18, 15, 26, 18],
         [15, 12, 21, 17],
         [27, 15, 14, 16]],

        [[24, 38, 33, 37],
         [17, 40, 43, 18],
         [30, 21, 20, 29]],

        [[43, 49, 33, 43],
         [43, 45, 44, 35],
         [48, 42, 32, 36]]]])

In [66]:
arr

array([[[[28, 14, 42, 42],
         [11, 35, 32, 21],
         [31, 40, 25, 35]],

        [[41, 10, 17, 16],
         [38, 31, 13, 15],
         [12, 18, 31, 32]],

        [[30, 19, 43, 22],
         [10, 11, 18, 41],
         [11, 29, 26, 36]]],


       [[[24, 38, 33, 37],
         [43, 45, 21, 35],
         [30, 42, 20, 29]],

        [[43, 15, 26, 43],
         [15, 12, 43, 17],
         [48, 15, 32, 16]],

        [[18, 49, 33, 18],
         [17, 40, 44, 18],
         [27, 21, 14, 36]]]])

In [67]:
np.sort(arr, axis =2)

array([[[[11, 14, 25, 21],
         [28, 35, 32, 35],
         [31, 40, 42, 42]],

        [[12, 10, 13, 15],
         [38, 18, 17, 16],
         [41, 31, 31, 32]],

        [[10, 11, 18, 22],
         [11, 19, 26, 36],
         [30, 29, 43, 41]]],


       [[[24, 38, 20, 29],
         [30, 42, 21, 35],
         [43, 45, 33, 37]],

        [[15, 12, 26, 16],
         [43, 15, 32, 17],
         [48, 15, 43, 43]],

        [[17, 21, 14, 18],
         [18, 40, 33, 18],
         [27, 49, 44, 36]]]])

In [68]:
arr

array([[[[28, 14, 42, 42],
         [11, 35, 32, 21],
         [31, 40, 25, 35]],

        [[41, 10, 17, 16],
         [38, 31, 13, 15],
         [12, 18, 31, 32]],

        [[30, 19, 43, 22],
         [10, 11, 18, 41],
         [11, 29, 26, 36]]],


       [[[24, 38, 33, 37],
         [43, 45, 21, 35],
         [30, 42, 20, 29]],

        [[43, 15, 26, 43],
         [15, 12, 43, 17],
         [48, 15, 32, 16]],

        [[18, 49, 33, 18],
         [17, 40, 44, 18],
         [27, 21, 14, 36]]]])

In [69]:
np.sort(arr, axis=3)

array([[[[14, 28, 42, 42],
         [11, 21, 32, 35],
         [25, 31, 35, 40]],

        [[10, 16, 17, 41],
         [13, 15, 31, 38],
         [12, 18, 31, 32]],

        [[19, 22, 30, 43],
         [10, 11, 18, 41],
         [11, 26, 29, 36]]],


       [[[24, 33, 37, 38],
         [21, 35, 43, 45],
         [20, 29, 30, 42]],

        [[15, 26, 43, 43],
         [12, 15, 17, 43],
         [15, 16, 32, 48]],

        [[18, 18, 33, 49],
         [17, 18, 40, 44],
         [14, 21, 27, 36]]]])

In [73]:
arr

array([[[[28, 14, 42, 42],
         [11, 35, 32, 21],
         [31, 40, 25, 35]],

        [[41, 10, 17, 16],
         [38, 31, 13, 15],
         [12, 18, 31, 32]],

        [[30, 19, 43, 22],
         [10, 11, 18, 41],
         [11, 29, 26, 36]]],


       [[[24, 38, 33, 37],
         [43, 45, 21, 35],
         [30, 42, 20, 29]],

        [[43, 15, 26, 43],
         [15, 12, 43, 17],
         [48, 15, 32, 16]],

        [[18, 49, 33, 18],
         [17, 40, 44, 18],
         [27, 21, 14, 36]]]])

## Stacking/Concatenating Arrays

In [78]:
#np.hstack((arr1, arr2))

In [87]:
arr1 = np.zeros((2, 3, 4))
arr2 = np.ones((6, 4))

In [41]:
np.vstack((arr1, arr2))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
arr1 = np.zeros((4, 4))
arr2 = np.ones((2, 4))
np.concatenate((arr1, arr2), axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Adding/Removing Axis

In [89]:
np.concatenate((arr1, arr2.reshape(2, 3, 4)), axis=1).shape

(2, 6, 4)

In [90]:
#Add new axis to existing array or vector...
v = np.arange(5)
v

array([0, 1, 2, 3, 4])

In [92]:
v = v[:, np.newaxis]
v

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [93]:
v = v[:, np.newaxis]
v

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [95]:
v.squeeze(axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [96]:
arr

array([[[[28, 14, 42, 42],
         [11, 35, 32, 21],
         [31, 40, 25, 35]],

        [[41, 10, 17, 16],
         [38, 31, 13, 15],
         [12, 18, 31, 32]],

        [[30, 19, 43, 22],
         [10, 11, 18, 41],
         [11, 29, 26, 36]]],


       [[[24, 38, 33, 37],
         [43, 45, 21, 35],
         [30, 42, 20, 29]],

        [[43, 15, 26, 43],
         [15, 12, 43, 17],
         [48, 15, 32, 16]],

        [[18, 49, 33, 18],
         [17, 40, 44, 18],
         [27, 21, 14, 36]]]])

In [101]:
arr.squeeze(axis=3)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [102]:
# This is the same as saying arr[1,:,:]
print(arr[1,...])

[[[24 38 33 37]
  [43 45 21 35]
  [30 42 20 29]]

 [[43 15 26 43]
  [15 12 43 17]
  [48 15 32 16]]

 [[18 49 33 18]
  [17 40 44 18]
  [27 21 14 36]]]


In [103]:
arr[arr%2==0]

array([28, 14, 42, 42, 32, 40, 10, 16, 38, 12, 18, 32, 30, 22, 10, 18, 26,
       36, 24, 38, 30, 42, 20, 26, 12, 48, 32, 16, 18, 18, 40, 44, 18, 14,
       36])

## Mathematical Functions

In [36]:
#index of maximum value...
np.argmax(arr)

39

In [37]:
#index of minimum value...
np.argmin(arr)

0

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sum(arr)

45

In [5]:
np.multiply(arr, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
np.divide(arr, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [10]:
np.remainder(arr, 2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [11]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
np.power(arr, 5)

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
np.log(arr)

/home/malang/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [18]:
#mat1: No of columns = mat2:  No of rows...
mat1 = np.arange(20).reshape(5, 4)
mat2 = np.arange(8).reshape(4, 2)
np.dot(mat1, mat2)

array([[ 28,  34],
       [ 76,  98],
       [124, 162],
       [172, 226],
       [220, 290]])

In [19]:
np.var(mat1)

33.25

In [20]:
np.std(mat1)

5.766281297335398

In [21]:
np.array_equal(mat1, mat2)

False

In [22]:
mat1 == mat2

/home/malang/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

## Multidimensional Transpose

In [23]:
arr = np.arange(80).reshape(4, 5, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [25]:
arr[[0, 2]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [27]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [26]:
arr.T

array([[[ 0, 20, 40, 60],
        [ 4, 24, 44, 64],
        [ 8, 28, 48, 68],
        [12, 32, 52, 72],
        [16, 36, 56, 76]],

       [[ 1, 21, 41, 61],
        [ 5, 25, 45, 65],
        [ 9, 29, 49, 69],
        [13, 33, 53, 73],
        [17, 37, 57, 77]],

       [[ 2, 22, 42, 62],
        [ 6, 26, 46, 66],
        [10, 30, 50, 70],
        [14, 34, 54, 74],
        [18, 38, 58, 78]],

       [[ 3, 23, 43, 63],
        [ 7, 27, 47, 67],
        [11, 31, 51, 71],
        [15, 35, 55, 75],
        [19, 39, 59, 79]]])

In [28]:
np.append(arr, arr.T)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,  0, 20, 40, 60,  4,
       24, 44, 64,  8, 28, 48, 68, 12, 32, 52, 72, 16, 36, 56, 76,  1, 21,
       41, 61,  5, 25, 45, 65,  9, 29, 49, 69, 13, 33, 53, 73, 17, 37, 57,
       77,  2, 22, 42, 62,  6, 26, 46, 66, 10, 30, 50, 70, 14, 34, 54, 74,
       18, 38, 58, 78,  3, 23, 43, 63,  7, 27, 47, 67, 11, 31, 51, 71, 15,
       35, 55, 75, 19, 39, 59, 79])

## Array Broadcasting 

In [34]:
tarr = np.array([1, 2, 3, 4])
arr + tarr

array([[[ 1,  3,  5,  7],
        [ 5,  7,  9, 11],
        [ 9, 11, 13, 15],
        [13, 15, 17, 19],
        [17, 19, 21, 23]],

       [[21, 23, 25, 27],
        [25, 27, 29, 31],
        [29, 31, 33, 35],
        [33, 35, 37, 39],
        [37, 39, 41, 43]],

       [[41, 43, 45, 47],
        [45, 47, 49, 51],
        [49, 51, 53, 55],
        [53, 55, 57, 59],
        [57, 59, 61, 63]],

       [[61, 63, 65, 67],
        [65, 67, 69, 71],
        [69, 71, 73, 75],
        [73, 75, 77, 79],
        [77, 79, 81, 83]]])

In [35]:
arr * tarr

array([[[  0,   2,   6,  12],
        [  4,  10,  18,  28],
        [  8,  18,  30,  44],
        [ 12,  26,  42,  60],
        [ 16,  34,  54,  76]],

       [[ 20,  42,  66,  92],
        [ 24,  50,  78, 108],
        [ 28,  58,  90, 124],
        [ 32,  66, 102, 140],
        [ 36,  74, 114, 156]],

       [[ 40,  82, 126, 172],
        [ 44,  90, 138, 188],
        [ 48,  98, 150, 204],
        [ 52, 106, 162, 220],
        [ 56, 114, 174, 236]],

       [[ 60, 122, 186, 252],
        [ 64, 130, 198, 268],
        [ 68, 138, 210, 284],
        [ 72, 146, 222, 300],
        [ 76, 154, 234, 316]]])